version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  install-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run: npm i
      - run: ng test
      - run: ng e2e
workflows:
  run-tests:
    jobs:
      - install-and-test


