version: '2.1'
orbs:
  cypress: cypress-io/cypress@1.27.0
jobs:
  install-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install nodejs npm
      - run: export NG_CLI_ANALYTICS=ci 
      - run: sudo npm i -g @angular/cli > /dev/null
      - run: npm i
      - run: ng config -g cli.warnings.versionMismatch false
      - run: ng test
workflows:
  run-tests:
    jobs:
      - install-and-test
      - cypress/run:
          yarn: false
          start: npm start
          wait-on: 'http://localhost:4200'
          store_artifacts: true


