version: '2.1'
orbs:
  cypress: cypress-io/cypress@1.27.0
jobs:
  install-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: npm i -g @angular/cli
      - run: npm i
      - run: ng test
workflows:
  run-tests:
    jobs:
      - install-and-test
      - cypress/run:
         yarn: false


