version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
  ng-test:
    docker:
      - image: 'cimg/base:stable'
    steps: 
      - run: ng test
workflows:
  test_my_app:
    jobs:
      - ng-test
      - install-node
